from micropython import const

DESCRIPTOR = const((
	b"\x05\x01"  # Usage Page (Generic Desktop Ctrls)
	b"\x09\x06"  # Usage (Keyboard)
	b"\xA1\x01"  # Collection (Application)
	b"\x85\x01"  #   Report ID (1)
	b"\x05\x07"  #   Usage Page (Kbrd/Keypad)
	b"\x19\xE0"  #   Usage Minimum (\xE0)
	b"\x29\xE7"  #   Usage Maximum (\xE7)
	b"\x15\x00"  #   Logical Minimum (0)
	b"\x25\x01"  #   Logical Maximum (1)
	b"\x75\x01"  #   Report Size (1)
	b"\x95\x08"  #   Report Count (8)
	b"\x81\x02"  #   Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
	b"\x81\x01"  #   Input (Const,Array,Abs,No Wrap,Linear,Preferred State,No Null Position)
	b"\x19\x00"  #   Usage Minimum (\x00)
	b"\x29\x89"  #   Usage Maximum (\x89)
	b"\x15\x00"  #   Logical Minimum (0)
	b"\x25\x89"  #   Logical Maximum (137)
	b"\x75\x08"  #   Report Size (8)
	b"\x95\x06"  #   Report Count (6)
	b"\x81\x00"  #   Input (Data,Array,Abs,No Wrap,Linear,Preferred State,No Null Position)
	b"\x05\x08"  #   Usage Page (LEDs)
	b"\x19\x01"  #   Usage Minimum (Num Lock)
	b"\x29\x05"  #   Usage Maximum (Kana)
	b"\x15\x00"  #   Logical Minimum (0)
	b"\x25\x01"  #   Logical Maximum (1)
	b"\x75\x01"  #   Report Size (1)
	b"\x95\x05"  #   Report Count (5)
	b"\x91\x02"  #   Output (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position,Non-volatile)
	b"\x95\x03"  #   Report Count (3)
	b"\x91\x01"  #   Output (Const,Array,Abs,No Wrap,Linear,Preferred State,No Null Position,Non-volatile)
	b"\xC0"  # End Collection
))
